version: 0.2

phases:
  install:
    commands:
      - apt-get update && apt-get install -y unzip
      - curl -LO https://releases.hashicorp.com/terraform/1.5.0/terraform_1.5.0_linux_amd64.zip
      - unzip terraform_1.5.0_linux_amd64.zip
      - mv terraform /usr/local/bin/
  build:
    commands:
      - cd src && zip -r ../output/lambda_function.zip . && cd ..
      - cd dependencies && zip -rg ../output/lambda_function.zip . && cd ..
      - ls -la output/
      - cd infra
      - terraform init
      - terraform validate
      - terraform plan -out=tfplan -input=false
  post_build:
    commands:
      - terraform apply -input=false tfplan
