version: 0.2

phases:
  build:
    commands:
      - echo "=== Diretório atual ==="
      - pwd
      - echo "=== Conteúdo da pasta ==="
      - ls -l
      - echo "=== Subpastas ==="
      - ls -l ../
      - echo "=== Entrando na pasta infra ==="
      - cd infra || exit 1
      - ls -l
